import type { Product, CategoryCircleItem, TrustItem } from "@/types";

export type SubCategory = {
  id: string;
  name: string;
  slug: string;
  description?: string;
};

export type CategoryMeta = {
  id: string;
  name: string;
  slug: string;
  headline: string;
  description: string;
  bannerImage?: string;
  showAgeFilter?: boolean;
  subcategories: SubCategory[];
};

export type NavDepartment = {
  name: string;
  slug: string;
  href: string;
  icon: string;
  badge?: string;
  description: string;
  subcategories: {
    name: string;
    slug: string;
    href: string;
    description: string;
    icon: string;
  }[];
};

export const NAV_DEPARTMENTS: NavDepartment[] = [
  {
    name: "Baby & Kids",
    slug: "baby-kids",
    href: "/category/baby-kids",
    icon: "Baby",
    description: "Developmental toys, vehicles, puzzles & nursery essentials",
    subcategories: [
      {
        name: "Educational & STEM Toys",
        slug: "educational-toys",
        href: "/category/educational-toys",
        description: "Montessori wooden boards, circuit kits & sensory puzzles",
        icon: "Puzzle",
      },
      {
        name: "Cars & Vehicles",
        slug: "cars-vehicles",
        href: "/category/cars-vehicles",
        description: "Magnetic modular racers, RC stunt cars & wooden trains",
        icon: "Car",
      },
      {
        name: "Unique & Kinetic Toys",
        slug: "unique-toys",
        href: "/category/unique-toys",
        description: "Kinetic balance sculptures, optical illusions & marble runs",
        icon: "Sparkles",
      },
      {
        name: "Puzzles & Brain Games",
        slug: "puzzles-games",
        href: "/category/puzzles-games",
        description: "Brainteasers, logic challenges & sensory sorting sets",
        icon: "Gamepad2",
      },
      {
        name: "Newborn & Toddler Essentials",
        slug: "newborn-babies",
        href: "/category/newborn-babies",
        description: "Organic rattles, teething sets & nursery milestone keepsakes",
        icon: "Heart",
      },
    ],
  },
  {
    name: "Gift Combos",
    slug: "gift-combos",
    href: "/category/gift-combos",
    icon: "Gift",
    description: "Curated celebration bundles, surprise packs & ready-to-gift sets",
    subcategories: [
      {
        name: "Newborn Baby Hampers",
        slug: "newborn-babies",
        href: "/category/gift-combos?sub=newborn-babies",
        description: "Gentle organic rattles, swaddle sets & milestone boxes",
        icon: "Baby",
      },
      {
        name: "Birthday Celebration Boxes",
        slug: "birthday-babies",
        href: "/category/gift-combos?sub=birthday-babies",
        description: "All-in-one party surprise packs & festive developmental bundles",
        icon: "PartyPopper",
      },
      {
        name: "Home Decor Gift Sets",
        slug: "home-decor-gifts",
        href: "/category/gift-combos?sub=home-decor-gifts",
        description: "Ambient glow lamps & artisanal aesthetic sculptures",
        icon: "Lamp",
      },
      {
        name: "Smart Gadget Kits",
        slug: "gadget-bundles",
        href: "/category/gift-combos?sub=gadget-bundles",
        description: "Multi-device smart exploration kits & coding sets",
        icon: "Bot",
      },
    ],
  },
  {
    name: "Digital Gadgets",
    slug: "digital-gadgets",
    href: "/category/digital-gadgets",
    icon: "Cpu",
    description: "Smart learning companions, planetariums & tech desk gadgets",
    subcategories: [
      {
        name: "Planetarium & Projectors",
        slug: "planetarium-lights",
        href: "/category/digital-gadgets?sub=planetarium-lights",
        description: "High-definition galaxy projectors & star atmosphere lamps",
        icon: "Moon",
      },
      {
        name: "Coding & Robotics",
        slug: "coding-robots",
        href: "/category/digital-gadgets?sub=coding-robots",
        description: "Interactive coding bots & smart AI companions for kids",
        icon: "Bot",
      },
      {
        name: "Kids Smartwatches & Audio",
        slug: "smart-audio",
        href: "/category/digital-gadgets?sub=kids-smartwatches",
        description: "Kid-safe audio gadgets & interactive music creators",
        icon: "Headphones",
      },
      {
        name: "Smart Desk Tech",
        slug: "desk-tech",
        href: "/category/digital-gadgets?sub=desk-tech",
        description: "Minimalist desktop timers, clocks & sensory ambient lighting",
        icon: "Clock",
      },
    ],
  },
  {
    name: "Home Decor",
    slug: "home-decor",
    href: "/category/home-decor",
    icon: "Home",
    description: "Aesthetic nursery accents, ambient glow lamps & desk art",
    subcategories: [
      {
        name: "Ambient Lighting",
        slug: "ambient-lighting",
        href: "/category/home-decor?sub=ambient-lighting",
        description: "Artisanal mushroom lamps & soothing night lights",
        icon: "Lamp",
      },
      {
        name: "Wall Art & Shelves",
        slug: "wall-shelves",
        href: "/category/home-decor?sub=wall-shelves",
        description: "Floating cloud shelves & geometric wall accents",
        icon: "LayoutGrid",
      },
      {
        name: "Kinetic Desk Sculptures",
        slug: "kinetic-sculptures",
        href: "/category/home-decor?sub=kinetic-sculptures",
        description: "Perpetual motion balance sculptures & kinetic desktop art",
        icon: "Orbit",
      },
      {
        name: "Nursery Accents",
        slug: "nursery-decor",
        href: "/category/home-decor?sub=nursery-decor",
        description: "Playroom mobiles, storage organizers & decorative accents",
        icon: "Sparkles",
      },
    ],
  },
];

export const CATEGORIES_META: Record<string, CategoryMeta> = {
  "all": {
    id: "cat-all",
    name: "All Categories",
    slug: "all",
    headline: "Explore Our Full Curated Collection",
    description: "Discover handcrafted Montessori toys, STEM electronic gadgets, ambient home decor, and ready-to-gift celebration hampers.",
    showAgeFilter: false,
    subcategories: [
      { id: "sub-all-1", name: "Baby & Kids", slug: "baby-kids" },
      { id: "sub-all-2", name: "Gift Combos", slug: "gift-combos" },
      { id: "sub-all-3", name: "Digital Gadgets", slug: "digital-gadgets" },
      { id: "sub-all-4", name: "Home Decor", slug: "home-decor" },
      { id: "sub-all-5", name: "Deals Zone", slug: "deals" },
    ],
  },
  "baby-kids": {
    id: "cat-baby-kids",
    name: "Baby & Kids",
    slug: "baby-kids",
    headline: "Developmental Toys, Vehicles & Nursery Essentials",
    description: "Foster spatial reasoning, motor coordination, cognitive logic, and joyful discovery with curated Montessori and STEM tools.",
    showAgeFilter: true,
    subcategories: [
      { id: "sub-bk-1", name: "Educational & STEM Toys", slug: "educational-toys", description: "Montessori wooden boards, circuit kits & sensory puzzles" },
      { id: "sub-bk-2", name: "Cars & Vehicles", slug: "cars-vehicles", description: "Magnetic modular racers, RC stunt cars & wooden trains" },
      { id: "sub-bk-3", name: "Unique & Kinetic Toys", slug: "unique-toys", description: "Kinetic balance sculptures, optical illusions & marble runs" },
      { id: "sub-bk-4", name: "Puzzles & Brain Games", slug: "puzzles-games", description: "Brainteasers, logic challenges & sensory sorting sets" },
      { id: "sub-bk-5", name: "Newborn & Toddler Essentials", slug: "newborn-babies", description: "Organic rattles, teething sets & nursery milestone keepsakes" },
    ],
  },
  "gift-combos": {
    id: "c1111111-1111-1111-1111-111111111111",
    name: "Gift Combos",
    slug: "gift-combos",
    headline: "Curated Celebration Bundles & Ready-to-Gift Sets",
    description: "Thoughtfully assembled surprise packs, organic newborn hampers, birthday boxes, and smart gadget combos.",
    showAgeFilter: true,
    subcategories: [
      { id: "c1111111-1111-1111-1111-111111111112", name: "Newborn Baby Hampers", slug: "newborn-babies", description: "Gentle organic rattles, teether sets, and nursery keepsakes" },
      { id: "c1111111-1111-1111-1111-111111111113", name: "Birthday Celebration Boxes", slug: "birthday-babies", description: "All-in-one party surprise packs and celebratory bundles" },
      { id: "c1111111-1111-1111-1111-111111111114", name: "Home Decor Gift Sets", slug: "home-decor-gifts", description: "Ambient lamps and aesthetic desktop sculptures" },
      { id: "c1111111-1111-1111-1111-111111111115", name: "Smart Gadget Kits", slug: "gadget-bundles", description: "Multi-device smart exploration kits and robotic sets" },
    ],
  },
  "newborn-babies": {
    id: "c1111111-1111-1111-1111-111111111112",
    name: "Newborn & Toddler Essentials",
    slug: "newborn-babies",
    headline: "Pure & Organic Milestone Keepsakes",
    description: "Gentle organic cotton swaddles, handmade crochet rattles, and natural beechwood milestone sets for newborns.",
    showAgeFilter: true,
    subcategories: [
      { id: "sub-nb-1", name: "Organic Swaddles", slug: "newborn-babies" },
      { id: "sub-nb-2", name: "Sensory Rattles", slug: "newborn-babies" },
      { id: "sub-nb-3", name: "Milestone Cards", slug: "newborn-babies" },
    ],
  },
  "birthday-babies": {
    id: "c1111111-1111-1111-1111-111111111113",
    name: "Birthday Celebrations",
    slug: "birthday-babies",
    headline: "Unforgettable Birthday Surprise Boxes",
    description: "Packed with wonder, developmental games, and cheerful celebration items for toddlers and kids.",
    showAgeFilter: true,
    subcategories: [
      { id: "sub-bb-1", name: "Party Sets", slug: "birthday-babies" },
      { id: "sub-bb-2", name: "STEM Birthday Bundles", slug: "birthday-babies" },
    ],
  },
  "home-decor-gifts": {
    id: "c1111111-1111-1111-1111-111111111114",
    name: "Home Decor Gifts",
    slug: "home-decor-gifts",
    headline: "Warm Ambient Lights & Modern Accent Pieces",
    description: "Artisanal glow lamps, kinetic perpetual sculptures, and aesthetic nursery mobiles.",
    showAgeFilter: false,
    subcategories: [
      { id: "sub-hdg-1", name: "Night Lights", slug: "home-decor-gifts" },
      { id: "sub-hdg-2", name: "Desk Sculptures", slug: "home-decor-gifts" },
    ],
  },
  "gadget-bundles": {
    id: "c1111111-1111-1111-1111-111111111115",
    name: "Gadget Bundles",
    slug: "gadget-bundles",
    headline: "Interactive STEM Kits & Smart Toy Bundles",
    description: "Curated smart gadgets, planetarium projectors, and coding companions packaged together.",
    showAgeFilter: false,
    subcategories: [
      { id: "sub-gb-1", name: "Coding & Robotics", slug: "gadget-bundles" },
      { id: "sub-gb-2", name: "Projectors & Audio", slug: "gadget-bundles" },
    ],
  },
  "educational-toys": {
    id: "c2222222-2222-2222-2222-222222222222",
    name: "Educational & STEM Toys",
    slug: "educational-toys",
    headline: "Montessori & STEM Brain-Building Toys",
    description: "Foster spatial reasoning, motor coordination, cognitive logic, and imaginative problem-solving.",
    showAgeFilter: true,
    subcategories: [
      { id: "sub-edu-1", name: "Montessori Wooden", slug: "educational-toys" },
      { id: "sub-edu-2", name: "STEM Electronics", slug: "educational-toys" },
      { id: "sub-edu-3", name: "Sensory Puzzles", slug: "educational-toys" },
      { id: "sub-edu-4", name: "Language & Math", slug: "educational-toys" },
    ],
  },
  "cars-vehicles": {
    id: "c3333333-3333-3333-3333-333333333333",
    name: "Cars & Vehicles",
    slug: "cars-vehicles",
    headline: "Magnetic Speedsters, RC Racers & Wooden Railways",
    description: "High-precision diecast models, modular magnetic vehicles, and smooth-rolling tracks.",
    showAgeFilter: true,
    subcategories: [
      { id: "sub-car-1", name: "Magnetic Modular", slug: "cars-vehicles" },
      { id: "sub-car-2", name: "RC Stunt Cars", slug: "cars-vehicles" },
      { id: "sub-car-3", name: "Wooden Trains", slug: "cars-vehicles" },
    ],
  },
  "unique-toys": {
    id: "c4444444-4444-4444-4444-444444444444",
    name: "Unique & Kinetic Toys",
    slug: "unique-toys",
    headline: "Whimsical Kinetic Art, Illusions & Brainteasers",
    description: "Mesmerizing balance sculptures, optical puzzles, and magnetic marble circuits.",
    showAgeFilter: true,
    subcategories: [
      { id: "sub-uniq-1", name: "Kinetic Sculptures", slug: "unique-toys" },
      { id: "sub-uniq-2", name: "Optical Illusions", slug: "unique-toys" },
      { id: "sub-uniq-3", name: "Marble Runs", slug: "unique-toys" },
    ],
  },
  "puzzles-games": {
    id: "cat-puzzles-games",
    name: "Puzzles & Brain Games",
    slug: "puzzles-games",
    headline: "Tactile Brainteasers & Cognitive Logic Games",
    description: "Multi-level spatial challenges, sensory shape sorting, and family board games.",
    showAgeFilter: true,
    subcategories: [
      { id: "sub-pg-1", name: "Sensory Sorting", slug: "puzzles-games" },
      { id: "sub-pg-2", name: "3D Wooden Teasers", slug: "puzzles-games" },
      { id: "sub-pg-3", name: "Logic Boards", slug: "puzzles-games" },
    ],
  },
  "home-decor": {
    id: "c5555555-5555-5555-5555-555555555555",
    name: "Home Decor",
    slug: "home-decor",
    headline: "Aesthetic Nursery Accents & Ambient Illumination",
    description: "Playful mushroom lamps, cloud floating shelves, minimalist perpetual calendars, and geometric wall art.",
    showAgeFilter: false,
    subcategories: [
      { id: "sub-hd-1", name: "Ambient Lighting", slug: "home-decor" },
      { id: "sub-hd-2", name: "Wall Art & Shelves", slug: "home-decor" },
      { id: "sub-hd-3", name: "Kinetic Desk Sculptures", slug: "home-decor" },
      { id: "sub-hd-4", name: "Nursery Accents", slug: "home-decor" },
    ],
  },
  "digital-gadgets": {
    id: "c6666666-6666-6666-6666-666666666666",
    name: "Digital Gadgets",
    slug: "digital-gadgets",
    headline: "Smart Learning Companions & Starry Projectors",
    description: "Cutting-edge kids coding bots, high-definition galaxy planetariums, and interactive sound generators.",
    showAgeFilter: false,
    subcategories: [
      { id: "sub-dg-1", name: "Planetarium & Projectors", slug: "digital-gadgets" },
      { id: "sub-dg-2", name: "Coding & Robotics", slug: "digital-gadgets" },
      { id: "sub-dg-3", name: "Kids Smartwatches & Audio", slug: "digital-gadgets" },
      { id: "sub-dg-4", name: "Smart Desk Tech", slug: "digital-gadgets" },
    ],
  },
  "deals": {
    id: "cat-deals",
    name: "Deals Zone",
    slug: "deals",
    headline: "Limited-Time Offers & Exclusive Discounts",
    description: "Special prices on curated bestsellers, bundles, and seasonal developmental toys.",
    showAgeFilter: false,
    subcategories: [
      { id: "sub-dl-1", name: "Flash Sales", slug: "deals" },
      { id: "sub-dl-2", name: "Bundle Discounts", slug: "deals" },
      { id: "sub-dl-3", name: "Clearance", slug: "deals" },
    ],
  },
  "new-arrivals": {
    id: "cat-new",
    name: "New Arrivals",
    slug: "new-arrivals",
    headline: "Freshly Curated Additions for Curious Minds",
    description: "Check out the newest educational discoveries, toys, and aesthetic additions to Mirai Mart.",
    showAgeFilter: false,
    subcategories: [
      { id: "sub-na-1", name: "This Month", slug: "new-arrivals" },
      { id: "sub-na-2", name: "Trending Now", slug: "new-arrivals" },
    ],
  },
  "best-sellers": {
    id: "cat-best",
    name: "Best Sellers",
    slug: "best-sellers",
    headline: "Most-Loved Picks by Parents & Creators",
    description: "Top-rated Montessori boards, galaxy projectors, gift hampers, and vehicles loved by hundreds of families.",
    showAgeFilter: false,
    subcategories: [
      { id: "sub-bs-1", name: "Top Rated 5★", slug: "best-sellers" },
      { id: "sub-bs-2", name: "Parent Favorites", slug: "best-sellers" },
    ],
  },
};

export const CATEGORY_CIRCLES: CategoryCircleItem[] = [
  {
    id: "cat-1",
    name: "Baby & Kids",
    slug: "baby-kids",
    imageUrl: "/images/cat-baby-kids.svg",
  },
  {
    id: "cat-2",
    name: "Gift Combos",
    slug: "gift-combos",
    imageUrl: "/images/cat-arts-crafts.svg",
  },
  {
    id: "cat-3",
    name: "Digital Gadgets",
    slug: "digital-gadgets",
    imageUrl: "/images/cat-smart-gadgets.svg",
  },
  {
    id: "cat-4",
    name: "Home Decor",
    slug: "home-decor",
    imageUrl: "/images/cat-home-decor.svg",
  },
  {
    id: "cat-5",
    name: "Deals Zone",
    slug: "deals",
    imageUrl: "/images/cat-all-categories.svg",
  },
];

export const TRUST_ITEMS: TrustItem[] = [
  {
    icon: "gem",
    title: "Curated with Care",
    description: "Handpicked quality products for your loved ones",
  },
  {
    icon: "shield",
    title: "Safe & Certified",
    description: "All products are child-safe and quality tested",
  },
  {
    icon: "truck",
    title: "Fast Delivery",
    description: "Free delivery across Bangladesh over ৳ 999",
  },
  {
    icon: "rotate",
    title: "Hassle Free Returns",
    description: "30 days easy return and replacement policy",
  },
];

export interface ProductReview {
  id: string;
  productId?: string;
  author: string;
  rating: number;
  date: string;
  title: string;
  comment: string;
  verified: boolean;
  avatarUrl?: string;
  helpfulCount: number;
}

export const MOCK_REVIEWS: ProductReview[] = [
  {
    id: "rev-1",
    author: "Nusrat Jahan",
    rating: 5,
    date: "2 days ago",
    title: "Exceptional craftsmanship and baby-safe quality!",
    comment: "The wood finish is silky smooth without any sharp edges or splinters. My 2-year-old was captivated immediately, sorting by color and shape. Delivery in Dhaka took less than 24 hours!",
    verified: true,
    helpfulCount: 24,
  },
  {
    id: "rev-2",
    author: "Tanvir Ahmed",
    rating: 5,
    date: "1 week ago",
    title: "Worth every Taka — very engaging for kids",
    comment: "Super premium packaging and excellent attention to detail. Ordered via WhatsApp and the support team was very prompt and polite. Highly recommended for parents looking for screen-free educational toys.",
    verified: true,
    helpfulCount: 18,
  },
  {
    id: "rev-3",
    author: "Farhana Chowdhury",
    rating: 4,
    date: "2 weeks ago",
    title: "Beautiful aesthetic and durable",
    comment: "Looks gorgeous in our Montessori nursery playroom. Solid weight and rich natural colors that don't chip or fade. My toddler plays with it every single morning.",
    verified: true,
    helpfulCount: 12,
  },
  {
    id: "rev-4",
    author: "Mahmud Hasan",
    rating: 5,
    date: "3 weeks ago",
    title: "Perfect birthday gift package",
    comment: "Purchased this as a gift for my nephew's birthday. It arrived in pristine condition with lovely wrapping. The parents loved it so much!",
    verified: true,
    helpfulCount: 9,
  },
];

export const ALL_PRODUCTS: Product[] = [
  {
    id: "a1111111-1111-1111-1111-111111111111",
    title: "Montessori Wooden Geometry Sorting Board",
    slug: "montessori-wooden-geometry-sorting-board",
    category: "Educational Toys",
    categorySlug: "educational-toys",
    subCategorySlug: "educational-toys",
    price: 1450,
    compareAtPrice: 1850,
    rating: 4.9,
    reviewCount: 128,
    imageUrl: "https://images.unsplash.com/photo-1596461404969-9ae70f2830c1?q=80&w=800&auto=format&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1596461404969-9ae70f2830c1?q=80&w=1200&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1587654780291-39c9404d746b?q=80&w=1200&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?q=80&w=1200&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1560859251-d563a49c5e4a?q=80&w=1200&auto=format&fit=crop",
    ],
    badge: "Bestseller",
    ageRange: "1-3",
    tags: ["Montessori", "Sensory", "Eco-friendly"],
    sku: "MM-MNT-001",
    description: "Handcrafted from sustainable European beechwood, this sorting board fosters spatial reasoning, color recognition, and fine motor coordination in toddlers through tactile geometric exploration.",
    curatorNotes: "We love how the velvety non-toxic water-based finish feels in little hands. A timeless centerpiece for any Montessori play space that encourages hours of quiet, focused discovery.",
    features: [
      "Crafted from 100% sustainably harvested European solid beechwood",
      "Child-safe rounded chamfered corners with ultra-smooth hand-sanded finish",
      "Non-toxic organic vegetable-dye based water stains",
      "Develops pincer grip, hand-eye coordination, and spatial logic",
      "Includes structured cotton canvas storage drawstring pouch",
    ],
    specs: {
      "Dimensions": "22.5 cm x 18.0 cm x 6.5 cm",
      "Weight": "680 grams",
      "Material": "Solid European Beechwood & Natural Water Stains",
      "Recommended Age": "12 months to 4 years",
      "Pieces Included": "16 geometric sorting blocks + 1 baseboard",
      "Care Instructions": "Wipe with a damp cloth; do not submerge in water",
      "Origin": "Ethically Crafted in Sustainable Workshops",
      "Warranty": "6 Months Replacement Guarantee",
    },
    safetyCertifications: [
      "EN71 European Toy Safety Standard Certified",
      "ASTM F963 US Toy Safety Compliant",
      "100% BPA, PVC, Lead & Phthalate Free",
      "FSC Certified Sustainable Forestry Wood",
    ],
    inBoxItems: [
      "1x Solid Beechwood Multi-Slot Sorting Base",
      "16x Vibrant Color-Coded Geometric Prisms",
      "1x Heavy-Duty Natural Cotton Canvas Travel Pouch",
      "1x Montessori Parent Activity Guide with 12 Play Stages",
    ],
    variants: [
      {
        id: "var-mnt-1",
        sku: "MM-MNT-001-NAT",
        title: "Natural Beechwood (16-Piece)",
        price: 1450,
        compareAtPrice: 1850,
        stockQuantity: 18,
        attributes: { "Finish": "Natural Wood", "Size": "Standard 16pc" },
        images: [
          "https://images.unsplash.com/photo-1596461404969-9ae70f2830c1?q=80&w=1200&auto=format&fit=crop",
          "https://images.unsplash.com/photo-1587654780291-39c9404d746b?q=80&w=1200&auto=format&fit=crop",
        ],
        isDefault: true,
      },
      {
        id: "var-mnt-2",
        sku: "MM-MNT-001-PAS",
        title: "Pastel Dream Rainbow (24-Piece Deluxe)",
        price: 1850,
        compareAtPrice: 2300,
        stockQuantity: 9,
        attributes: { "Finish": "Pastel Rainbow", "Size": "Deluxe 24pc" },
        images: [
          "https://images.unsplash.com/photo-1587654780291-39c9404d746b?q=80&w=1200&auto=format&fit=crop",
          "https://images.unsplash.com/photo-1596461404969-9ae70f2830c1?q=80&w=1200&auto=format&fit=crop",
        ],
      },
      {
        id: "var-mnt-3",
        sku: "MM-MNT-001-PRI",
        title: "Vibrant Primary Montessori (32-Piece Master)",
        price: 2250,
        compareAtPrice: 2800,
        stockQuantity: 4,
        attributes: { "Finish": "Primary Colors", "Size": "Master 32pc" },
        images: [
          "https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?q=80&w=1200&auto=format&fit=crop",
          "https://images.unsplash.com/photo-1596461404969-9ae70f2830c1?q=80&w=1200&auto=format&fit=crop",
        ],
      },
    ],
  },
  {
    id: "a2222222-2222-2222-2222-222222222222",
    title: "Astronaut Star Galaxy Planetarium Projector",
    slug: "astronaut-star-galaxy-planetarium-projector",
    category: "Digital Gadgets",
    categorySlug: "digital-gadgets",
    subCategorySlug: "gadget-bundles",
    price: 2350,
    compareAtPrice: 2950,
    rating: 4.8,
    reviewCount: 95,
    imageUrl: "https://images.unsplash.com/photo-1550745165-9bc0b252726f?q=80&w=800&auto=format&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1550745165-9bc0b252726f?q=80&w=1200&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1513519245088-0e12902e5a38?q=80&w=1200&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1534447677768-be436bb09401?q=80&w=1200&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1507499739999-097706ad8914?q=80&w=1200&auto=format&fit=crop",
    ],
    badge: "-20%",
    ageRange: "3-5",
    tags: ["STEM", "Creative", "Smart"],
    sku: "MM-GDG-002",
    description: "High-definition galaxy light projector with magnetic 360° rotating head, custom nebula color flows, timer function, and soothing white noise presets.",
    curatorNotes: "Projects crystal-clear constellations across ceilings up to 300 sq ft. The magnetic astronaut head articulates smoothly to aim anywhere in the room without awkward angles.",
    features: [
      "360° Magnetic Articulated Astronaut Helmet for omnidirectional ceiling projection",
      "8 Mesmerizing Nebula Color Modes with adjustable speed and brightness",
      "High-precision laser star mapping engine with dual breathing light effects",
      "Intelligent sleep timer (45 min / 90 min auto shutoff)",
      "Multi-function wireless remote controller included",
    ],
    specs: {
      "Dimensions": "12.0 cm x 11.3 cm x 22.8 cm",
      "Weight": "490 grams",
      "Power Input": "USB Type-C 5V / 1A",
      "Projection Range": "15 to 50 square meters (up to 300 sq ft)",
      "Control Mode": "Remote Control & Tactile Base Buttons",
      "Laser Wavelength": "532nm (Class 1 Safe Eye Rating)",
      "Warranty": "1 Year Replacement Warranty",
    },
    safetyCertifications: [
      "FCC & CE Electronics Safety Certified",
      "RoHS Compliant Eco Materials",
      "Eye-Safe Diffused Optical Lens",
    ],
    inBoxItems: [
      "1x Astronaut Galaxy Projector Unit",
      "1x Lunar Surface Weighted Base Stand",
      "1x Infrared Wireless Remote Controller",
      "1x 1.5m USB-C Power Cable",
      "1x Comprehensive User Manual",
    ],
    variants: [
      {
        id: "var-ast-1",
        sku: "MM-GDG-002-WHT",
        title: "Lunar Pearl White",
        price: 2350,
        compareAtPrice: 2950,
        stockQuantity: 24,
        attributes: { "Color": "Lunar White" },
        images: ["https://images.unsplash.com/photo-1550745165-9bc0b252726f?q=80&w=1200&auto=format&fit=crop"],
        isDefault: true,
      },
      {
        id: "var-ast-2",
        sku: "MM-GDG-002-BLK",
        title: "Obsidian Space Black",
        price: 2490,
        compareAtPrice: 3100,
        stockQuantity: 12,
        attributes: { "Color": "Space Black" },
        images: ["https://images.unsplash.com/photo-1534447677768-be436bb09401?q=80&w=1200&auto=format&fit=crop"],
      },
    ],
  },
  {
    id: "a3333333-3333-3333-3333-333333333333",
    title: "Magnetic Aero Speedster Vehicle Kit",
    slug: "magnetic-aero-speedster-vehicle-kit",
    category: "Cars & Vehicles",
    categorySlug: "cars-vehicles",
    subCategorySlug: "cars-vehicles",
    price: 1850,
    compareAtPrice: 2300,
    rating: 4.9,
    reviewCount: 84,
    imageUrl: "https://images.unsplash.com/photo-1594787318286-3d835c1d207f?q=80&w=800&auto=format&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1594787318286-3d835c1d207f?q=80&w=1200&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1587654780291-39c9404d746b?q=80&w=1200&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1560859251-d563a49c5e4a?q=80&w=1200&auto=format&fit=crop",
    ],
    badge: "New",
    ageRange: "3-5",
    tags: ["STEM", "Kinetic", "Creative"],
    sku: "MM-CAR-003",
    description: "Interchangeable modular vehicle set with neodymium magnetic chassis, aerodynamic spoiler snap-ons, and whisper-quiet rubberized wheels.",
    curatorNotes: "Endless build variations allow young engineers to experiment with center-of-gravity and drag physics through hands-on play.",
    features: [
      "High-power encased Neodymium magnets for snappy, secure connections",
      "Interchangeable body shells, chassis, spoilers, and heavy-tread wheels",
      "Low-friction stainless steel wheel axles for long coasting distances",
      "Drop-tested impact-resistant ABS construction",
    ],
    specs: {
      "Dimensions": "18.0 cm x 9.5 cm x 7.0 cm (assembled)",
      "Weight": "420 grams",
      "Material": "Food-grade ABS & Neodymium N52 Magnets",
      "Recommended Age": "3+ years",
      "Pieces Included": "24 modular snap parts (builds 4 distinct vehicles)",
    },
    safetyCertifications: ["EN71 & ASTM F963 Certified", "Encapsulated Magnetic Safety Lock System"],
    inBoxItems: ["2x Magnetic Chassis", "6x Interchangeable Aerodynamic Bodies", "8x Low-Friction Wheels", "1x Track Ramp Stunt Guide"],
    variants: [
      {
        id: "var-car-1",
        sku: "MM-CAR-003-RCE",
        title: "Turbo Racer Pack (2-Car Kit)",
        price: 1850,
        compareAtPrice: 2300,
        stockQuantity: 15,
        attributes: { "Kit": "2-Car Turbo" },
        images: ["https://images.unsplash.com/photo-1594787318286-3d835c1d207f?q=80&w=1200&auto=format&fit=crop"],
        isDefault: true,
      },
      {
        id: "var-car-2",
        sku: "MM-CAR-003-SUP",
        title: "Grand Prix Master Pack (4-Car Deluxe Kit)",
        price: 3200,
        compareAtPrice: 3900,
        stockQuantity: 7,
        attributes: { "Kit": "4-Car Grand Prix" },
        images: ["https://images.unsplash.com/photo-1587654780291-39c9404d746b?q=80&w=1200&auto=format&fit=crop"],
      },
    ],
  },
  {
    id: "a4444444-4444-4444-4444-444444444444",
    title: "Kinetic Orbit Desktop Balance Sculpture",
    slug: "kinetic-orbit-desktop-balance-sculpture",
    category: "Unique Toys",
    categorySlug: "unique-toys",
    subCategorySlug: "home-decor-gifts",
    price: 2890,
    compareAtPrice: 3500,
    rating: 4.9,
    reviewCount: 56,
    imageUrl: "https://images.unsplash.com/photo-1558060370-d644479cb6f7?q=80&w=800&auto=format&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1558060370-d644479cb6f7?q=80&w=1200&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1513519245088-0e12902e5a38?q=80&w=1200&auto=format&fit=crop",
    ],
    badge: "Exclusive",
    ageRange: "8+",
    tags: ["Kinetic", "Creative"],
    sku: "MM-KIN-004",
    description: "Perpetual-motion inspired desktop kinetic sculpture machined from anodized aerospace aluminum and high-precision ceramic ball bearings.",
    curatorNotes: "An entrancing visual stress-reliever for creative desks and modern living rooms. Spins smoothly for minutes with a single gentle nudge.",
    features: [
      "Ultra-low friction hybrid ceramic ball bearings",
      "CNC precision-machined aircraft grade 6061-T6 aluminum",
      "Silent, mesmerizing gyroscopic motion",
      "Matte satin anodized scratch-resistant coating",
    ],
    specs: {
      "Dimensions": "15.0 cm x 15.0 cm x 20.5 cm",
      "Weight": "510 grams",
      "Material": "Anodized Aerospace Aluminum & Ceramic Bearings",
      "Origin": "Precision CNC Crafted",
    },
    safetyCertifications: ["Lead-Free Certified Alloy", "ISO 9001 Manufacturing"],
    inBoxItems: ["1x Kinetic Orbit Sculpture Unit", "1x Heavyweighted Machined Base", "1x Microfiber Polishing Cloth"],
    variants: [
      {
        id: "var-kin-1",
        sku: "MM-KIN-004-MET",
        title: "Space Gray Anodized",
        price: 2890,
        compareAtPrice: 3500,
        stockQuantity: 10,
        attributes: { "Color": "Space Gray" },
        images: ["https://images.unsplash.com/photo-1558060370-d644479cb6f7?q=80&w=1200&auto=format&fit=crop"],
        isDefault: true,
      },
      {
        id: "var-kin-2",
        sku: "MM-KIN-004-GLD",
        title: "Champagne Gold Edition",
        price: 3150,
        compareAtPrice: 3800,
        stockQuantity: 5,
        attributes: { "Color": "Champagne Gold" },
        images: ["https://images.unsplash.com/photo-1513519245088-0e12902e5a38?q=80&w=1200&auto=format&fit=crop"],
      },
    ],
  },
  {
    id: "a5555555-5555-5555-5555-555555555555",
    title: "Deluxe Newborn Organic Milestone Gift Hamper",
    slug: "deluxe-newborn-organic-milestone-gift-hamper",
    category: "Gift Combos",
    categorySlug: "gift-combos",
    subCategorySlug: "newborn-babies",
    price: 3850,
    compareAtPrice: 4500,
    rating: 5.0,
    reviewCount: 67,
    imageUrl: "https://images.unsplash.com/photo-1549465220-1a8b9238cd48?q=80&w=800&auto=format&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1549465220-1a8b9238cd48?q=80&w=1200&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?q=80&w=1200&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1587654780291-39c9404d746b?q=80&w=1200&auto=format&fit=crop",
    ],
    badge: "Bestseller",
    ageRange: "0-1",
    tags: ["Sensory", "Eco-friendly"],
    sku: "MM-GFT-005",
    description: "Complete celebratory baby gift set presented in a reusable keepsake woven cotton basket, including organic cotton swaddles, crochet rattle, and milestone wood disks.",
    curatorNotes: "Curated with zero plastics and hypoallergenic materials. Packaged in an artisanal cotton hamper with a custom hand-lettered greeting card.",
    features: [
      "100% GOTS Certified Organic Muslin Swaddle Blankets",
      "Handmade crochet rattle with soothing natural bell sound",
      "Natural laser-engraved birch milestone photo disks (Months 1–12)",
      "Presented in a reusable handwoven cotton rope nursery basket",
    ],
    specs: {
      "Hamper Dimensions": "32.0 cm x 24.0 cm x 16.0 cm",
      "Weight": "1.15 kg",
      "Fabric": "GOTS Certified 100% Organic Cotton",
      "Wood": "Natural Beech & Birchwood",
    },
    safetyCertifications: ["OEKO-TEX Standard 100 Class 1 (Baby)", "GOTS Organic Certified"],
    inBoxItems: [
      "2x Organic Muslin Swaddles (120x120cm)",
      "1x Hand-Crocheted Bunny Teething Rattle",
      "12x Double-Sided Milestone Keepsake Disks",
      "1x Reusable Woven Rope Nursery Basket",
      "1x Mirai Mart Luxury Embossed Greeting Card",
    ],
    variants: [
      {
        id: "var-gft-1",
        sku: "MM-GFT-005-SGE",
        title: "Sage & Cloud White Hamper",
        price: 3850,
        compareAtPrice: 4500,
        stockQuantity: 14,
        attributes: { "Theme": "Sage & White" },
        images: ["https://images.unsplash.com/photo-1549465220-1a8b9238cd48?q=80&w=1200&auto=format&fit=crop"],
        isDefault: true,
      },
      {
        id: "var-gft-2",
        sku: "MM-GFT-005-TER",
        title: "Warm Terracotta & Honey Hamper",
        price: 3950,
        compareAtPrice: 4650,
        stockQuantity: 8,
        attributes: { "Theme": "Terracotta Honey" },
        images: ["https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?q=80&w=1200&auto=format&fit=crop"],
      },
    ],
  },
  {
    id: "a6666666-6666-6666-6666-666666666666",
    title: "Nordic Minimalist Mushroom Bedside Glow Lamp",
    slug: "nordic-minimalist-mushroom-bedside-glow-lamp",
    category: "Home Decor",
    categorySlug: "home-decor",
    subCategorySlug: "home-decor-gifts",
    price: 2150,
    compareAtPrice: 2650,
    rating: 4.7,
    reviewCount: 42,
    imageUrl: "https://images.unsplash.com/photo-1513519245088-0e12902e5a38?q=80&w=800&auto=format&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1513519245088-0e12902e5a38?q=80&w=1200&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1550745165-9bc0b252726f?q=80&w=1200&auto=format&fit=crop",
    ],
    badge: "-15%",
    ageRange: "all",
    tags: ["Creative", "Eco-friendly"],
    sku: "MM-DEC-006",
    description: "Soft dimmable ambient glow lamp with touch-capacitive base, warm 2700K LED glow, and 18-hour rechargeable lithium-ion battery life.",
    curatorNotes: "The soft-touch frosted acrylic shade diffuses warm light evenly without harsh glare — ideal for peaceful nursery nights and reading corners.",
    features: [
      "Touch-capacitive stepless dimming (10% to 100% brightness)",
      "3 CCT Color temperatures: Warm Amber (2200K), Warm White (2700K), Daylight (4000K)",
      "Rechargeable 2600mAh battery offering up to 24 hours runtime",
      "Matte powder-coated spun metal base with non-slip silicone footpad",
    ],
    specs: {
      "Dimensions": "16.0 cm diameter x 21.0 cm height",
      "Weight": "580 grams",
      "Battery": "2600mAh Li-ion (USB-C Rechargeable)",
      "Battery Life": "8 to 24 hours depending on brightness",
      "Warranty": "1 Year Warranty",
    },
    safetyCertifications: ["CE & RoHS Certified", "Flicker-Free Eye Safety Testing"],
    inBoxItems: ["1x Nordic Mushroom Lamp", "1x USB-C Braided Charging Cable", "1x Quick Start Guide"],
    variants: [
      {
        id: "var-lmp-1",
        sku: "MM-DEC-006-CRM",
        title: "Matte Warm Cream",
        price: 2150,
        compareAtPrice: 2650,
        stockQuantity: 16,
        attributes: { "Color": "Warm Cream" },
        images: ["https://images.unsplash.com/photo-1513519245088-0e12902e5a38?q=80&w=1200&auto=format&fit=crop"],
        isDefault: true,
      },
      {
        id: "var-lmp-2",
        sku: "MM-DEC-006-TER",
        title: "Terracotta Rust",
        price: 2250,
        compareAtPrice: 2750,
        stockQuantity: 7,
        attributes: { "Color": "Terracotta Rust" },
        images: ["https://images.unsplash.com/photo-1513519245088-0e12902e5a38?q=80&w=1200&auto=format&fit=crop"],
      },
    ],
  },
  {
    id: "a7777777-7777-7777-7777-777777777777",
    title: "RoboCode Companion Programmable Bot",
    slug: "robocode-companion-programmable-bot",
    category: "Digital Gadgets",
    categorySlug: "digital-gadgets",
    subCategorySlug: "gadget-bundles",
    price: 3250,
    compareAtPrice: 3800,
    rating: 4.9,
    reviewCount: 210,
    imageUrl: "https://images.unsplash.com/photo-1550745165-9bc0b252726f?q=80&w=800&auto=format&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1550745165-9bc0b252726f?q=80&w=1200&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1587654780291-39c9404d746b?q=80&w=1200&auto=format&fit=crop",
    ],
    badge: "Bestseller",
    ageRange: "5-8",
    tags: ["STEM", "Smart", "Creative"],
    sku: "MM-ROB-007",
    description: "Voice-responsive coding companion robot with drag-and-drop visual logic cards, obstacle-avoidance sonar sensors, and expressive LED matrix eyes.",
    curatorNotes: "Teaches algorithmic thinking and sequential logic without requiring screen time. Kids arrange magnetic command tiles and watch the robot execute missions.",
    features: [
      "100% Screen-free coding through tactile magnetic command tiles",
      "Ultrasonic obstacle avoidance and edge detection sensors",
      "Expressive customizable LED animated eye displays",
      "Interactive maze mapping & challenge mission booklet",
    ],
    specs: {
      "Dimensions": "14.0 cm x 13.0 cm x 11.5 cm",
      "Weight": "620 grams",
      "Power": "USB-C Rechargeable (4 Hours Active Play)",
      "Sensors": "Sonar Rangefinder, Optical Line Tracker, Sound Sensor",
    },
    safetyCertifications: ["ASTM F963 & EN71 Safety Standards", "Class 1 Sensor Rating"],
    inBoxItems: ["1x RoboCode Bot", "32x Magnetic Coding Tiles", "1x Double-Sided Activity Playmat", "1x 40-Mission Adventure Book", "1x USB-C Cable"],
    variants: [
      {
        id: "var-rob-1",
        sku: "MM-ROB-007-BLU",
        title: "Cyber Blue Edition",
        price: 3250,
        compareAtPrice: 3800,
        stockQuantity: 11,
        attributes: { "Color": "Cyber Blue" },
        images: ["https://images.unsplash.com/photo-1550745165-9bc0b252726f?q=80&w=1200&auto=format&fit=crop"],
        isDefault: true,
      },
    ],
  },
  {
    id: "a8888888-8888-8888-8888-888888888888",
    title: "Artisanal Wooden Train Express Deluxe Network",
    slug: "artisanal-wooden-train-express-deluxe-network",
    category: "Cars & Vehicles",
    categorySlug: "cars-vehicles",
    subCategorySlug: "cars-vehicles",
    price: 2450,
    compareAtPrice: 2990,
    rating: 4.8,
    reviewCount: 74,
    imageUrl: "https://images.unsplash.com/photo-1594787318286-3d835c1d207f?q=80&w=800&auto=format&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1594787318286-3d835c1d207f?q=80&w=1200&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1596461404969-9ae70f2830c1?q=80&w=1200&auto=format&fit=crop",
    ],
    badge: "New",
    ageRange: "3-5",
    tags: ["Montessori", "Eco-friendly", "Creative"],
    sku: "MM-TRN-008",
    description: "48-piece solid birchwood track system featuring magnetic engine carriages, bridge arches, turnouts, and realistic scenery elements.",
    curatorNotes: "100% compatible with universal wooden railway tracks. The silky hand-sanded edges ensure safe, splinter-free railway building for hours.",
    features: [
      "48 Solid Beechwood Precision-Cut Tracks & Scenery Parts",
      "Strong magnetic coupling on locomotive and freight carriages",
      "Elevation bridge piers and suspension track pieces",
      "Universal fit compatible with Brio, Thomas, and Melissa & Doug tracks",
    ],
    specs: {
      "Track Layout Size": "105 cm x 72 cm (oval configuration)",
      "Weight": "1.8 kg",
      "Material": "FSC Certified Birchwood & Solid Steel Axles",
    },
    safetyCertifications: ["EN71 & ASTM F963 Toy Safety", "Non-Toxic Water Based Paint"],
    inBoxItems: ["32x Wooden Tracks", "1x Steam Engine + 3x Magnetic Wagons", "8x Scenery Trees & Signs", "4x Bridge Piers"],
    variants: [
      {
        id: "var-trn-1",
        sku: "MM-TRN-008-STD",
        title: "Deluxe 48-Piece Network",
        price: 2450,
        compareAtPrice: 2990,
        stockQuantity: 15,
        attributes: { "Set": "48-Piece Deluxe" },
        images: ["https://images.unsplash.com/photo-1594787318286-3d835c1d207f?q=80&w=1200&auto=format&fit=crop"],
        isDefault: true,
      },
    ],
  },
  {
    id: "a9999999-9999-9999-9999-999999999999",
    title: "Sensory Organic Cotton Swaddle & Teether Bundle",
    slug: "sensory-organic-cotton-swaddle-teether-bundle",
    category: "Gift Combos",
    categorySlug: "gift-combos",
    subCategorySlug: "newborn-babies",
    price: 1950,
    compareAtPrice: 2400,
    rating: 4.9,
    reviewCount: 88,
    imageUrl: "https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?q=80&w=800&auto=format&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?q=80&w=1200&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1549465220-1a8b9238cd48?q=80&w=1200&auto=format&fit=crop",
    ],
    badge: "Bestseller",
    ageRange: "0-1",
    tags: ["Sensory", "Eco-friendly"],
    sku: "MM-GFT-009",
    description: "Breathable GOTS-certified organic cotton muslin blanket paired with a food-grade silicone teething ring and beechwood clip.",
    curatorNotes: "Hypoallergenic, thermoregulating, and machine washable. An essential gift pairing for baby showers and early sensory bonding.",
    features: [
      "Ultra-soft 4-layer pre-washed organic cotton muslin",
      "Natural beechwood teether with food-grade textured silicone beads",
      "Breathable open weave prevents overheating",
    ],
    specs: {
      "Swaddle Size": "120 cm x 120 cm",
      "Material": "100% GOTS Organic Cotton + Food-Grade Silicone",
    },
    safetyCertifications: ["OEKO-TEX Standard 100", "BPA & Phthalate Free Certified"],
    inBoxItems: ["1x Organic Muslin Swaddle", "1x Sensory Teething Rattle Ring", "1x Keepsake Gift Bag"],
    variants: [
      {
        id: "var-swd-1",
        sku: "MM-GFT-009-OAK",
        title: "Oatmeal Neutral",
        price: 1950,
        compareAtPrice: 2400,
        stockQuantity: 20,
        attributes: { "Color": "Oatmeal" },
        images: ["https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?q=80&w=1200&auto=format&fit=crop"],
        isDefault: true,
      },
    ],
  },
  {
    id: "b1010101-1010-1010-1010-101010101010",
    title: "Magnetic Marble Run Kinetic Construction Set",
    slug: "magnetic-marble-run-kinetic-construction-set",
    category: "Unique Toys",
    categorySlug: "unique-toys",
    subCategorySlug: "unique-toys",
    price: 2650,
    compareAtPrice: 3200,
    rating: 4.8,
    reviewCount: 63,
    imageUrl: "https://images.unsplash.com/photo-1558060370-d644479cb6f7?q=80&w=800&auto=format&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1558060370-d644479cb6f7?q=80&w=1200&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1587654780291-39c9404d746b?q=80&w=1200&auto=format&fit=crop",
    ],
    badge: "Sale",
    ageRange: "5-8",
    tags: ["STEM", "Kinetic", "Creative"],
    sku: "MM-UNQ-010",
    description: "Translucent magnetic building blocks with winding chutes, vortex funnels, and LED glowing marbles that illuminate the track in the dark.",
    curatorNotes: "Teaches kinetic energy conservation, gravity acceleration, and structural engineering in a dazzling colorful spectacle.",
    features: [
      "72-Piece Modular Magnetic Tiles & Clear Tubing System",
      "4x LED Glow-in-the-dark Light Marbles",
      "Extra-strong welded seams on magnetic tiles prevent breakages",
    ],
    specs: {
      "Weight": "1.3 kg",
      "Material": "BPA-Free Non-Toxic Polycarbonate & N48 Magnets",
      "Recommended Age": "4+ years",
    },
    safetyCertifications: ["EN71 & ASTM F963 Certified", "Sonic Welded Magnetic Pockets"],
    inBoxItems: ["48x Magnetic Tile Connectors", "24x Curved Chutes & Funnels", "4x LED Light Marbles", "4x Wooden Solid Marbles"],
    variants: [
      {
        id: "var-mbr-1",
        sku: "MM-UNQ-010-72P",
        title: "72-Piece Glow Master Kit",
        price: 2650,
        compareAtPrice: 3200,
        stockQuantity: 18,
        attributes: { "Kit": "72-Piece Set" },
        images: ["https://images.unsplash.com/photo-1558060370-d644479cb6f7?q=80&w=1200&auto=format&fit=crop"],
        isDefault: true,
      },
    ],
  },
  {
    id: "b2020202-2020-2020-2020-202020202020",
    title: "Cloud Floating Wooden Wall Shelf",
    slug: "cloud-floating-wooden-wall-shelf",
    category: "Home Decor",
    categorySlug: "home-decor",
    subCategorySlug: "home-decor",
    price: 1250,
    compareAtPrice: 1550,
    rating: 4.6,
    reviewCount: 38,
    imageUrl: "https://images.unsplash.com/photo-1513519245088-0e12902e5a38?q=80&w=800&auto=format&fit=crop",
    images: ["https://images.unsplash.com/photo-1513519245088-0e12902e5a38?q=80&w=1200&auto=format&fit=crop"],
    ageRange: "all",
    tags: ["Creative", "Eco-friendly"],
    sku: "MM-DEC-011",
    description: "Whimsical Scandinavian cloud silhouette floating bookshelf crafted from durable MDF with smooth matte lacquer finish.",
    curatorNotes: "Adds a dreamy, organized accent to nurseries, bedrooms, and study corners with hidden wall mounting hardware included.",
    features: ["Solid Scandinavian pine and high-density MDF", "Hidden keyhole wall mount brackets for seamless floating look"],
    specs: { "Dimensions": "45.0 cm x 12.0 cm x 25.0 cm", "Weight Capacity": "5 kg" },
    safetyCertifications: ["Low VOC Water-Based Paint"],
    inBoxItems: ["1x Cloud Shelf", "2x Heavy Duty Drywall Anchors & Screws", "1x Alignment Stencil"],
    variants: [
      {
        id: "var-cld-1",
        sku: "MM-DEC-011-WHT",
        title: "Pure White Cloud",
        price: 1250,
        compareAtPrice: 1550,
        stockQuantity: 12,
        attributes: { "Color": "Pure White" },
        images: ["https://images.unsplash.com/photo-1513519245088-0e12902e5a38?q=80&w=1200&auto=format&fit=crop"],
        isDefault: true,
      },
    ],
  },
  {
    id: "b3030303-3030-3030-3030-303030303030",
    title: "Celebration Birthday STEM Gift Mega Pack",
    slug: "celebration-birthday-stem-gift-mega-pack",
    category: "Gift Combos",
    categorySlug: "gift-combos",
    subCategorySlug: "birthday-babies",
    price: 4250,
    compareAtPrice: 5200,
    rating: 5.0,
    reviewCount: 49,
    imageUrl: "https://images.unsplash.com/photo-1513151233558-d860c5398176?q=80&w=800&auto=format&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1513151233558-d860c5398176?q=80&w=1200&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1550745165-9bc0b252726f?q=80&w=1200&auto=format&fit=crop",
    ],
    badge: "Exclusive",
    ageRange: "5-8",
    tags: ["STEM", "Creative"],
    sku: "MM-GFT-012",
    description: "The ultimate birthday gift hamper featuring a mini robotic kit, building tiles, celebration confetti card, and celebratory gift packaging.",
    curatorNotes: "Takes the stress out of birthday gifting. Packed with creative wonder and wrapped in festive sunny yellow ribbons.",
    features: ["All-in-one deluxe gift wrapping included", "Combines robotics, puzzles, and celebration surprise items"],
    specs: { "Box Size": "35 cm x 28 cm x 18 cm", "Weight": "1.6 kg" },
    safetyCertifications: ["Toy Safety Certified EN71 / ASTM"],
    inBoxItems: ["1x Mini Robotics Kit", "1x 3D Magnetic Puzzle", "1x Birthday Card with Wax Seal", "1x Luxury Gift Hamper Box"],
    variants: [
      {
        id: "var-bdy-1",
        sku: "MM-GFT-012-DEL",
        title: "Celebration Master Box",
        price: 4250,
        compareAtPrice: 5200,
        stockQuantity: 9,
        attributes: { "Edition": "Deluxe Box" },
        images: ["https://images.unsplash.com/photo-1513151233558-d860c5398176?q=80&w=1200&auto=format&fit=crop"],
        isDefault: true,
      },
    ],
  },
  {
    id: "b4040404-4040-4040-4040-404040404040",
    title: "Interactive Smart Globe with Talking Pen",
    slug: "interactive-smart-globe-with-talking-pen",
    category: "Educational Toys",
    categorySlug: "educational-toys",
    subCategorySlug: "educational-toys",
    price: 2150,
    compareAtPrice: 2600,
    rating: 4.8,
    reviewCount: 112,
    imageUrl: "https://images.unsplash.com/photo-1596461404969-9ae70f2830c1?q=80&w=800&auto=format&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1596461404969-9ae70f2830c1?q=80&w=1200&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1550745165-9bc0b252726f?q=80&w=1200&auto=format&fit=crop",
    ],
    badge: "Bestseller",
    ageRange: "5-8",
    tags: ["STEM", "Smart"],
    sku: "MM-EDU-013",
    description: "Illuminated augmented reality world globe with touch-audio pen narrating countries, wildlife, landmarks, and cultural music in 5 languages.",
    curatorNotes: "Makes global geography come alive with quiz challenges, country facts, and a built-in warm LED constellation nightlight.",
    features: ["Optical touch-reading pen with HD speaker", "Over 1,000 recorded geographic facts and country anthems", "Dual mode: Daytime political map & Nighttime glowing constellation globe"],
    specs: { "Globe Diameter": "25.0 cm", "Power": "USB Powered & Rechargeable Pen", "Languages": "English & Bengali Audio Supported" },
    safetyCertifications: ["FCC & CE Certified", "Child-Safe Rounded Plastic Construction"],
    inBoxItems: ["1x AR Smart Globe", "1x Optical Talking Audio Pen", "1x Constellation Map Poster", "1x USB Cable"],
    variants: [
      {
        id: "var-glb-1",
        sku: "MM-EDU-013-STD",
        title: "25cm Illuminated Edition",
        price: 2150,
        compareAtPrice: 2600,
        stockQuantity: 15,
        attributes: { "Size": "25cm Illuminated" },
        images: ["https://images.unsplash.com/photo-1596461404969-9ae70f2830c1?q=80&w=1200&auto=format&fit=crop"],
        isDefault: true,
      },
    ],
  },
  {
    id: "b5050505-5050-5050-5050-505050505050",
    title: "Mirai Smartwatch Kids GPS & Camera",
    slug: "mirai-smartwatch-kids-gps-camera",
    category: "Digital Gadgets",
    categorySlug: "digital-gadgets",
    subCategorySlug: "kids-smartwatches",
    price: 2750,
    compareAtPrice: 3400,
    rating: 4.7,
    reviewCount: 78,
    imageUrl: "https://images.unsplash.com/photo-1550745165-9bc0b252726f?q=80&w=800&auto=format&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1550745165-9bc0b252726f?q=80&w=1200&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1534447677768-be436bb09401?q=80&w=1200&auto=format&fit=crop",
    ],
    badge: "New",
    ageRange: "5-8",
    tags: ["Smart", "STEM"],
    sku: "MM-WCH-014",
    description: "Kid-safe 4G smartwatch with real-time location safety, two-way HD voice calling, SOS button, step tracker, and funny selfie filters.",
    curatorNotes: "Gives parents peace of mind and kids fun independence. Features water-resistant silicone strap and parental school-mode timer.",
    features: ["Real-time GPS/LBS/WiFi triple location tracking", "One-touch SOS emergency button", "IP67 Water-resistant rating", "Parental companion app with geofencing"],
    specs: { "Display": "1.4 inch HD IPS Touchscreen", "Battery": "680mAh (Up to 3 days standby)", "SIM Compatibility": "4G Nano SIM", "Strap": "Food-grade Silicone" },
    safetyCertifications: ["CE / SAR Radiation Tested Safe for Children", "IP67 Ingress Protection"],
    inBoxItems: ["1x Mirai Kids Smartwatch", "1x Magnetic Charging Cable", "1x SIM Ejector Tool", "1x User Manual"],
    variants: [
      {
        id: "var-wch-1",
        sku: "MM-WCH-014-BLU",
        title: "Ocean Sky Blue",
        price: 2750,
        compareAtPrice: 3400,
        stockQuantity: 14,
        attributes: { "Color": "Sky Blue" },
        images: ["https://images.unsplash.com/photo-1550745165-9bc0b252726f?q=80&w=1200&auto=format&fit=crop"],
        isDefault: true,
      },
      {
        id: "var-wch-2",
        sku: "MM-WCH-014-PNK",
        title: "Berry Pink",
        price: 2750,
        compareAtPrice: 3400,
        stockQuantity: 8,
        attributes: { "Color": "Berry Pink" },
        images: ["https://images.unsplash.com/photo-1550745165-9bc0b252726f?q=80&w=1200&auto=format&fit=crop"],
      },
    ],
  },
  {
    id: "b6060606-6060-6060-6060-606060606060",
    title: "Geometric Modern Wall Art Frame Set",
    slug: "geometric-modern-wall-art-frame-set",
    category: "Home Decor",
    categorySlug: "home-decor",
    subCategorySlug: "wall-shelves",
    price: 1890,
    compareAtPrice: 2250,
    rating: 4.9,
    reviewCount: 56,
    imageUrl: "https://images.unsplash.com/photo-1513519245088-0e12902e5a38?q=80&w=800&auto=format&fit=crop",
    images: ["https://images.unsplash.com/photo-1513519245088-0e12902e5a38?q=80&w=1200&auto=format&fit=crop"],
    ageRange: "all",
    tags: ["Creative"],
    sku: "MM-DEC-015",
    description: "Trio of museum-grade abstract prints in natural oakwood frames with non-glare shatterproof acrylic front.",
    curatorNotes: "Harmonious muted palettes tailored for contemporary living rooms, creative playrooms, and reading nooks.",
    features: ["Archival 300gsm cotton rag art paper", "Solid natural oak frames with pre-installed hanging hardware"],
    specs: { "Set Count": "3 Framed Prints", "Each Size": "30 cm x 40 cm (A3)" },
    safetyCertifications: ["Shatterproof Acrylic Front (Child-Safe)"],
    inBoxItems: ["3x Framed Art Prints", "6x Non-Trace Wall Hanging Hooks"],
    variants: [
      {
        id: "var-art-1",
        sku: "MM-DEC-015-OAK",
        title: "Trio Set in Natural Oak",
        price: 1890,
        compareAtPrice: 2250,
        stockQuantity: 10,
        attributes: { "Frame": "Natural Oak" },
        images: ["https://images.unsplash.com/photo-1513519245088-0e12902e5a38?q=80&w=1200&auto=format&fit=crop"],
        isDefault: true,
      },
    ],
  },
  {
    id: "b7070707-7070-7070-7070-707070707070",
    title: "Stunt RC Cyber Stuntbuggy 360",
    slug: "stunt-rc-cyber-stuntbuggy-360",
    category: "Cars & Vehicles",
    categorySlug: "cars-vehicles",
    subCategorySlug: "cars-vehicles",
    price: 1650,
    compareAtPrice: 2100,
    rating: 4.6,
    reviewCount: 47,
    imageUrl: "https://images.unsplash.com/photo-1594787318286-3d835c1d207f?q=80&w=800&auto=format&fit=crop",
    images: ["https://images.unsplash.com/photo-1594787318286-3d835c1d207f?q=80&w=1200&auto=format&fit=crop"],
    badge: "-20%",
    ageRange: "8+",
    tags: ["Kinetic", "STEM"],
    sku: "MM-CAR-016",
    description: "Double-sided tumbling RC vehicle with pneumatic oversized bounce tires, LED chassis underglow, and 2.4GHz remote.",
    curatorNotes: "Flips, spins, and drives over carpets, gravel, and steps without skipping a beat. USB rechargeable battery pack included.",
    features: ["360-degree high-speed rotation and double-sided flips", "2.4GHz interference-free remote control with 40m range"],
    specs: { "Speed": "Up to 15 km/h", "Battery": "3.7V 500mAh Li-Po", "Charge Time": "60 mins" },
    safetyCertifications: ["CE & FCC Compliant"],
    inBoxItems: ["1x RC Stuntbuggy", "1x 2.4GHz Remote", "2x Rechargeable Car Batteries", "1x USB Charger"],
    variants: [
      {
        id: "var-rc-1",
        sku: "MM-CAR-016-RED",
        title: "Neon Blaze Red",
        price: 1650,
        compareAtPrice: 2100,
        stockQuantity: 12,
        attributes: { "Color": "Neon Red" },
        images: ["https://images.unsplash.com/photo-1594787318286-3d835c1d207f?q=80&w=1200&auto=format&fit=crop"],
        isDefault: true,
      },
    ],
  },
  {
    id: "b8080808-8080-8080-8080-808080808080",
    title: "Wooden Stacking Rainbow Arc Bridge",
    slug: "wooden-stacking-rainbow-arc-bridge",
    category: "Educational Toys",
    categorySlug: "educational-toys",
    subCategorySlug: "educational-toys",
    price: 1350,
    compareAtPrice: 1700,
    rating: 4.9,
    reviewCount: 91,
    imageUrl: "https://images.unsplash.com/photo-1596461404969-9ae70f2830c1?q=80&w=800&auto=format&fit=crop",
    images: ["https://images.unsplash.com/photo-1596461404969-9ae70f2830c1?q=80&w=1200&auto=format&fit=crop"],
    badge: "Bestseller",
    ageRange: "1-3",
    tags: ["Montessori", "Sensory", "Eco-friendly"],
    sku: "MM-EDU-017",
    description: "12-piece open-ended nesting rainbow arches cut from solid lime wood and tinted with non-toxic water stains.",
    curatorNotes: "The pinnacle of Waldorf and Montessori open-ended play — becomes bridges, tunnels, doll cradles, and architectural towers.",
    features: ["12 hand-cut concentric nesting arches", "Velvety non-slip matte stain for easy building and stacking"],
    specs: { "Length": "36.0 cm", "Height": "18.0 cm", "Material": "Solid Lime Wood" },
    safetyCertifications: ["EN71 Certified", "100% Non-Toxic Natural Stains"],
    inBoxItems: ["12x Nesting Wooden Rainbow Arches", "1x Inspiration Creative Booklet"],
    variants: [
      {
        id: "var-rnb-1",
        sku: "MM-EDU-017-RNB",
        title: "12-Piece Classic Rainbow",
        price: 1350,
        compareAtPrice: 1700,
        stockQuantity: 16,
        attributes: { "Color": "Classic Rainbow" },
        images: ["https://images.unsplash.com/photo-1596461404969-9ae70f2830c1?q=80&w=1200&auto=format&fit=crop"],
        isDefault: true,
      },
    ],
  },
  {
    id: "b9090909-9090-9090-9090-909090909090",
    title: "Optical Prism Kaleidoscope Exploration Chamber",
    slug: "optical-prism-kaleidoscope-exploration-chamber",
    category: "Unique Toys",
    categorySlug: "unique-toys",
    subCategorySlug: "unique-toys",
    price: 1150,
    compareAtPrice: 1450,
    rating: 4.7,
    reviewCount: 34,
    imageUrl: "https://images.unsplash.com/photo-1558060370-d644479cb6f7?q=80&w=800&auto=format&fit=crop",
    images: ["https://images.unsplash.com/photo-1558060370-d644479cb6f7?q=80&w=1200&auto=format&fit=crop"],
    badge: "New",
    ageRange: "5-8",
    tags: ["STEM", "Creative"],
    sku: "MM-UNQ-018",
    description: "Handheld brass kaleidoscope with interchangeable crystal marble chambers and high-refraction optical glass prisms.",
    curatorNotes: "Transforms ordinary ambient room light and nature textures into breathtaking symmetrical mandalas.",
    features: ["Solid vintage brass casing", "Interchangeable clear optical glass marble tip", "3-Mirror internal prism reflection"],
    specs: { "Length": "18.5 cm", "Diameter": "3.8 cm", "Material": "Polished Brass & Optical Glass" },
    safetyCertifications: ["Lead-Free Brass Certified"],
    inBoxItems: ["1x Brass Kaleidoscope", "3x Swappable Optical Marble Spheres", "1x Velvet Pouch"],
    variants: [
      {
        id: "var-kld-1",
        sku: "MM-UNQ-018-BRS",
        title: "Vintage Polished Brass",
        price: 1150,
        compareAtPrice: 1450,
        stockQuantity: 14,
        attributes: { "Finish": "Polished Brass" },
        images: ["https://images.unsplash.com/photo-1558060370-d644479cb6f7?q=80&w=1200&auto=format&fit=crop"],
        isDefault: true,
      },
    ],
  },
];

export const FEATURED_PRODUCTS: Product[] = ALL_PRODUCTS.slice(0, 5);
export const TOP_PICKS_PRODUCTS: Product[] = ALL_PRODUCTS.slice(5, 10);

export const BRAND_LOGOS = [
  { name: "Fisher-Price", text: "Fisher-Price" },
  { name: "vtech", text: "vtech" },
  { name: "Melissa & Doug", text: "Melissa & Doug" },
  { name: "mideer", text: "mideer" },
  { name: "winfun", text: "winfun" },
];

