import type { Product, CategoryCircleItem, TrustItem } from "@/types";

export type SubCategory = {
  id: string;
  name: string;
  slug: string;
  description?: string;
};

export type CategoryMeta = {
  id: string;
  name: string;
  slug: string;
  headline: string;
  description: string;
  bannerImage?: string;
  subcategories: SubCategory[];
};

export const CATEGORIES_META: Record<string, CategoryMeta> = {
  "all": {
    id: "cat-all",
    name: "All Categories",
    slug: "all",
    headline: "Explore Our Full Curated Collection",
    description: "Discover handcrafted Montessori toys, STEM electronic gadgets, ambient home decor, and ready-to-gift celebration hampers.",
    subcategories: [
      { id: "sub-all-1", name: "Gift Combos", slug: "gift-combos" },
      { id: "sub-all-2", name: "Educational Toys", slug: "educational-toys" },
      { id: "sub-all-3", name: "Cars & Vehicles", slug: "cars-vehicles" },
      { id: "sub-all-4", name: "Unique Toys", slug: "unique-toys" },
      { id: "sub-all-5", name: "Home Decor", slug: "home-decor" },
      { id: "sub-all-6", name: "Digital Gadgets", slug: "digital-gadgets" },
    ],
  },
  "gift-combos": {
    id: "c1111111-1111-1111-1111-111111111111",
    name: "Gift Combos",
    slug: "gift-combos",
    headline: "Curated Celebration Bundles & Ready-to-Gift Sets",
    description: "Thoughtfully assembled surprise packs, organic newborn hampers, birthday boxes, and smart gadget combos.",
    subcategories: [
      { id: "c1111111-1111-1111-1111-111111111112", name: "Newborn Babies", slug: "newborn-babies", description: "Gentle organic rattles, teether sets, and nursery keepsakes" },
      { id: "c1111111-1111-1111-1111-111111111113", name: "Birthday Celebrations", slug: "birthday-babies", description: "All-in-one party surprise packs and celebratory bundles" },
      { id: "c1111111-1111-1111-1111-111111111114", name: "Home Decor Gifts", slug: "home-decor-gifts", description: "Ambient lamps and aesthetic desktop sculptures" },
      { id: "c1111111-1111-1111-1111-111111111115", name: "Gadget Bundles", slug: "gadget-bundles", description: "Multi-device smart exploration kits and robotic sets" },
    ],
  },
  "newborn-babies": {
    id: "c1111111-1111-1111-1111-111111111112",
    name: "Newborn Babies Gifts",
    slug: "newborn-babies",
    headline: "Pure & Organic Milestone Keepsakes",
    description: "Gentle organic cotton swaddles, handmade crochet rattles, and natural beechwood milestone sets for newborns.",
    subcategories: [
      { id: "sub-nb-1", name: "Organic Swaddles", slug: "newborn-babies" },
      { id: "sub-nb-2", name: "Sensory Rattles", slug: "newborn-babies" },
      { id: "sub-nb-3", name: "Milestone Cards", slug: "newborn-babies" },
    ],
  },
  "birthday-babies": {
    id: "c1111111-1111-1111-1111-111111111113",
    name: "Birthday Celebrations",
    slug: "birthday-babies",
    headline: "Unforgettable Birthday Surprise Boxes",
    description: "Packed with wonder, developmental games, and cheerful celebration items for toddlers and kids.",
    subcategories: [
      { id: "sub-bb-1", name: "Party Sets", slug: "birthday-babies" },
      { id: "sub-bb-2", name: "STEM Birthday Bundles", slug: "birthday-babies" },
    ],
  },
  "home-decor-gifts": {
    id: "c1111111-1111-1111-1111-111111111114",
    name: "Home Decor Gifts",
    slug: "home-decor-gifts",
    headline: "Warm Ambient Lights & Modern Accent Pieces",
    description: "Artisanal glow lamps, kinetic perpetual sculptures, and aesthetic nursery mobiles.",
    subcategories: [
      { id: "sub-hdg-1", name: "Night Lights", slug: "home-decor-gifts" },
      { id: "sub-hdg-2", name: "Desk Sculptures", slug: "home-decor-gifts" },
    ],
  },
  "gadget-bundles": {
    id: "c1111111-1111-1111-1111-111111111115",
    name: "Gadget Bundles",
    slug: "gadget-bundles",
    headline: "Interactive STEM Kits & Smart Toy Bundles",
    description: "Curated smart gadgets, planetarium projectors, and coding companions packaged together.",
    subcategories: [
      { id: "sub-gb-1", name: "Coding & Robotics", slug: "gadget-bundles" },
      { id: "sub-gb-2", name: "Projectors & Audio", slug: "gadget-bundles" },
    ],
  },
  "educational-toys": {
    id: "c2222222-2222-2222-2222-222222222222",
    name: "Educational Toys",
    slug: "educational-toys",
    headline: "Montessori & STEM Brain-Building Toys",
    description: "Foster spatial reasoning, motor coordination, cognitive logic, and imaginative problem-solving.",
    subcategories: [
      { id: "sub-edu-1", name: "Montessori Wooden", slug: "educational-toys" },
      { id: "sub-edu-2", name: "STEM Electronics", slug: "educational-toys" },
      { id: "sub-edu-3", name: "Sensory Puzzles", slug: "educational-toys" },
      { id: "sub-edu-4", name: "Language & Math", slug: "educational-toys" },
    ],
  },
  "cars-vehicles": {
    id: "c3333333-3333-3333-3333-333333333333",
    name: "Cars & Vehicles",
    slug: "cars-vehicles",
    headline: "Magnetic Speedsters, RC Racers & Wooden Railways",
    description: "High-precision diecast models, modular magnetic vehicles, and smooth-rolling tracks.",
    subcategories: [
      { id: "sub-car-1", name: "Magnetic Modular", slug: "cars-vehicles" },
      { id: "sub-car-2", name: "RC Stunt Cars", slug: "cars-vehicles" },
      { id: "sub-car-3", name: "Wooden Trains", slug: "cars-vehicles" },
    ],
  },
  "unique-toys": {
    id: "c4444444-4444-4444-4444-444444444444",
    name: "Unique Toys",
    slug: "unique-toys",
    headline: "Whimsical Kinetic Art, Illusions & Brainteasers",
    description: "Mesmerizing balance sculptures, optical puzzles, and magnetic marble circuits.",
    subcategories: [
      { id: "sub-uniq-1", name: "Kinetic Sculptures", slug: "unique-toys" },
      { id: "sub-uniq-2", name: "Optical Illusions", slug: "unique-toys" },
      { id: "sub-uniq-3", name: "Marble Runs", slug: "unique-toys" },
    ],
  },
  "home-decor": {
    id: "c5555555-5555-5555-5555-555555555555",
    name: "Home Decor",
    slug: "home-decor",
    headline: "Aesthetic Nursery Accents & Ambient Illumination",
    description: "Playful mushroom lamps, cloud floating shelves, minimalist perpetual calendars, and geometric wall art.",
    subcategories: [
      { id: "sub-hd-1", name: "Ambient Lighting", slug: "home-decor" },
      { id: "sub-hd-2", name: "Wall Art & Shelves", slug: "home-decor" },
      { id: "sub-hd-3", name: "Desk Accessories", slug: "home-decor" },
    ],
  },
  "digital-gadgets": {
    id: "c6666666-6666-6666-6666-666666666666",
    name: "Digital Gadgets",
    slug: "digital-gadgets",
    headline: "Smart Learning Companions & Starry Projectors",
    description: "Cutting-edge kids coding bots, high-definition galaxy planetariums, and interactive sound generators.",
    subcategories: [
      { id: "sub-dg-1", name: "Planetarium Lights", slug: "digital-gadgets" },
      { id: "sub-dg-2", name: "Kids Smartwatches", slug: "digital-gadgets" },
      { id: "sub-dg-3", name: "Coding Robots", slug: "digital-gadgets" },
    ],
  },
  "deals": {
    id: "cat-deals",
    name: "Deals Zone",
    slug: "deals",
    headline: "Limited-Time Offers & Exclusive Discounts",
    description: "Special prices on curated bestsellers, bundles, and seasonal developmental toys.",
    subcategories: [
      { id: "sub-dl-1", name: "Flash Sales", slug: "deals" },
      { id: "sub-dl-2", name: "Bundle Discounts", slug: "deals" },
      { id: "sub-dl-3", name: "Clearance", slug: "deals" },
    ],
  },
  "new-arrivals": {
    id: "cat-new",
    name: "New Arrivals",
    slug: "new-arrivals",
    headline: "Freshly Curated Additions for Curious Minds",
    description: "Check out the newest educational discoveries, toys, and aesthetic additions to Mirai Mart.",
    subcategories: [
      { id: "sub-na-1", name: "This Month", slug: "new-arrivals" },
      { id: "sub-na-2", name: "Trending Now", slug: "new-arrivals" },
    ],
  },
  "best-sellers": {
    id: "cat-best",
    name: "Best Sellers",
    slug: "best-sellers",
    headline: "Most-Loved Picks by Parents & Creators",
    description: "Top-rated Montessori boards, galaxy projectors, gift hampers, and vehicles loved by hundreds of families.",
    subcategories: [
      { id: "sub-bs-1", name: "Top Rated 5★", slug: "best-sellers" },
      { id: "sub-bs-2", name: "Parent Favorites", slug: "best-sellers" },
    ],
  },
  "toys-games": {
    id: "cat-tg",
    name: "Toys & Games",
    slug: "toys-games",
    headline: "Creative Play, Puzzles & Vehicle Adventures",
    description: "A wide assortment of wooden Montessori puzzles, kinetic toys, and magnetic vehicles.",
    subcategories: [
      { id: "sub-tg-1", name: "Educational", slug: "educational-toys" },
      { id: "sub-tg-2", name: "Vehicles", slug: "cars-vehicles" },
      { id: "sub-tg-3", name: "Unique Toys", slug: "unique-toys" },
    ],
  },
  "home-living": {
    id: "cat-hl",
    name: "Home & Living",
    slug: "home-living",
    headline: "Cozy Aesthetics & Playful Spaces",
    description: "Warm lights, organizers, decorative wall art, and ambient nursery additions.",
    subcategories: [
      { id: "sub-hl-1", name: "Lighting", slug: "home-decor" },
      { id: "sub-hl-2", name: "Wall Accents", slug: "home-decor" },
    ],
  },
  "baby-kids": {
    id: "cat-bk",
    name: "Baby & Kids",
    slug: "baby-kids",
    headline: "Gentle Developmental Play for Growing Little Ones",
    description: "Organic hampers, sensory rattles, sorting boards, and safe developmental items.",
    subcategories: [
      { id: "sub-bk-1", name: "Newborn 0-1", slug: "newborn-babies" },
      { id: "sub-bk-2", name: "Toddler 1-3", slug: "educational-toys" },
    ],
  },
  "smart-gadgets": {
    id: "cat-sg",
    name: "Smart Gadgets",
    slug: "smart-gadgets",
    headline: "Smart Electronics, Coding Companions & Projectors",
    description: "Interactive exploration gadgets designed to spark curiosity and technical thinking.",
    subcategories: [
      { id: "sub-sg-1", name: "Projectors", slug: "digital-gadgets" },
      { id: "sub-sg-2", name: "Coding Bots", slug: "digital-gadgets" },
    ],
  },
};

export const CATEGORY_CIRCLES: CategoryCircleItem[] = [
  {
    id: "cat-1",
    name: "Educational Toys",
    slug: "educational-toys",
    imageUrl: "/images/cat-educational.svg",
  },
  {
    id: "cat-2",
    name: "Smart Gadgets",
    slug: "digital-gadgets",
    imageUrl: "/images/cat-smart-gadgets.svg",
  },
  {
    id: "cat-3",
    name: "Gift Combos",
    slug: "gift-combos",
    imageUrl: "/images/cat-baby-kids.svg",
  },
  {
    id: "cat-4",
    name: "Home Decor",
    slug: "home-decor",
    imageUrl: "/images/cat-home-decor.svg",
  },
  {
    id: "cat-5",
    name: "Cars & Vehicles",
    slug: "cars-vehicles",
    imageUrl: "/images/cat-outdoor-play.svg",
  },
  {
    id: "cat-6",
    name: "Unique Toys",
    slug: "unique-toys",
    imageUrl: "/images/cat-arts-crafts.svg",
  },
  {
    id: "cat-7",
    name: "Newborn Gifts",
    slug: "newborn-babies",
    imageUrl: "/images/cat-puzzles-games.svg",
  },
  {
    id: "cat-8",
    name: "All Categories",
    slug: "all",
    imageUrl: "/images/cat-all-categories.svg",
  },
];

export const TRUST_ITEMS: TrustItem[] = [
  {
    icon: "gem",
    title: "Curated with Care",
    description: "Handpicked quality products for your loved ones",
  },
  {
    icon: "shield",
    title: "Safe & Certified",
    description: "All products are child-safe and quality tested",
  },
  {
    icon: "truck",
    title: "Fast Delivery",
    description: "Free delivery across Bangladesh over ৳ 999",
  },
  {
    icon: "rotate",
    title: "Hassle Free Returns",
    description: "30 days easy return and replacement policy",
  },
];

export const ALL_PRODUCTS: Product[] = [
  {
    id: "a1111111-1111-1111-1111-111111111111",
    title: "Montessori Wooden Geometry Sorting Board",
    slug: "montessori-wooden-geometry-sorting-board",
    category: "Educational Toys",
    categorySlug: "educational-toys",
    price: 1450,
    compareAtPrice: 1850,
    rating: 4.9,
    reviewCount: 128,
    imageUrl: "https://images.unsplash.com/photo-1596461404969-9ae70f2830c1?q=80&w=800&auto=format&fit=crop",
    badge: "Bestseller",
    ageRange: "1-3",
    tags: ["Montessori", "Sensory", "Eco-friendly"],
    description: "Handcrafted from sustainable European beechwood, this sorting board fosters spatial reasoning, color recognition, and fine motor coordination in toddlers.",
    curatorNotes: "We love how the velvety non-toxic water-based finish feels in little hands. A timeless centerpiece for any Montessori play space.",
  },
  {
    id: "a2222222-2222-2222-2222-222222222222",
    title: "Astronaut Star Galaxy Planetarium Projector",
    slug: "astronaut-star-galaxy-planetarium-projector",
    category: "Digital Gadgets",
    categorySlug: "digital-gadgets",
    subCategorySlug: "gadget-bundles",
    price: 2350,
    compareAtPrice: 2950,
    rating: 4.8,
    reviewCount: 95,
    imageUrl: "https://images.unsplash.com/photo-1550745165-9bc0b252726f?q=80&w=800&auto=format&fit=crop",
    badge: "-20%",
    ageRange: "3-5",
    tags: ["STEM", "Creative", "Smart"],
    description: "High-definition galaxy light projector with magnetic 360° rotating head, custom nebula color flows, and soothing white noise presets.",
    curatorNotes: "Projects crystal-clear constellations across ceilings up to 300 sq ft. The magnetic astronaut head articulates smoothly to aim anywhere in the room.",
  },
  {
    id: "a3333333-3333-3333-3333-333333333333",
    title: "Magnetic Aero Speedster Vehicle Kit",
    slug: "magnetic-aero-speedster-vehicle-kit",
    category: "Cars & Vehicles",
    categorySlug: "cars-vehicles",
    price: 1850,
    compareAtPrice: 2300,
    rating: 4.9,
    reviewCount: 84,
    imageUrl: "https://images.unsplash.com/photo-1594787318286-3d835c1d207f?q=80&w=800&auto=format&fit=crop",
    badge: "New",
    ageRange: "3-5",
    tags: ["STEM", "Kinetic", "Creative"],
    description: "Interchangeable modular vehicle set with neodymium magnetic chassis, aerodynamic spoiler snap-ons, and whisper-quiet rubberized wheels.",
    curatorNotes: "Endless build variations allow young engineers to experiment with center-of-gravity and drag physics through hands-on play.",
  },
  {
    id: "a4444444-4444-4444-4444-444444444444",
    title: "Kinetic Orbit Desktop Balance Sculpture",
    slug: "kinetic-orbit-desktop-balance-sculpture",
    category: "Unique Toys",
    categorySlug: "unique-toys",
    subCategorySlug: "home-decor-gifts",
    price: 2890,
    compareAtPrice: 3500,
    rating: 4.9,
    reviewCount: 56,
    imageUrl: "https://images.unsplash.com/photo-1558060370-d644479cb6f7?q=80&w=800&auto=format&fit=crop",
    badge: "Exclusive",
    ageRange: "8+",
    tags: ["Kinetic", "Creative"],
    description: "Perpetual-motion inspired desktop kinetic sculpture machined from anodized aerospace aluminum and high-precision ceramic ball bearings.",
    curatorNotes: "An entrancing visual stress-reliever for creative desks and modern living rooms. Spins smoothly for minutes with a single gentle nudge.",
  },
  {
    id: "a5555555-5555-5555-5555-555555555555",
    title: "Deluxe Newborn Organic Milestone Gift Hamper",
    slug: "deluxe-newborn-organic-milestone-gift-hamper",
    category: "Gift Combos",
    categorySlug: "gift-combos",
    subCategorySlug: "newborn-babies",
    price: 3850,
    compareAtPrice: 4500,
    rating: 5.0,
    reviewCount: 67,
    imageUrl: "https://images.unsplash.com/photo-1549465220-1a8b9238cd48?q=80&w=800&auto=format&fit=crop",
    badge: "Bestseller",
    ageRange: "0-1",
    tags: ["Sensory", "Eco-friendly"],
    description: "Complete celebratory baby gift set presented in a reusable keepsake woven cotton basket, including organic cotton swaddles, crochet rattle, and milestone wood disks.",
    curatorNotes: "Curated with zero plastics and hypoallergenic materials. Packaged in an artisanal cotton hamper with a custom hand-lettered greeting card.",
  },
  {
    id: "a6666666-6666-6666-6666-666666666666",
    title: "Nordic Minimalist Mushroom Bedside Glow Lamp",
    slug: "nordic-minimalist-mushroom-bedside-glow-lamp",
    category: "Home Decor",
    categorySlug: "home-decor",
    subCategorySlug: "home-decor-gifts",
    price: 2150,
    compareAtPrice: 2650,
    rating: 4.7,
    reviewCount: 42,
    imageUrl: "https://images.unsplash.com/photo-1513519245088-0e12902e5a38?q=80&w=800&auto=format&fit=crop",
    badge: "-15%",
    ageRange: "all",
    tags: ["Creative", "Eco-friendly"],
    description: "Soft dimmable ambient glow lamp with touch-capacitive base, warm 2700K LED glow, and 18-hour rechargeable lithium-ion battery life.",
    curatorNotes: "The soft-touch frosted acrylic shade diffuses warm light evenly without harsh glare — ideal for peaceful nursery nights and reading corners.",
  },
  {
    id: "a7777777-7777-7777-7777-777777777777",
    title: "RoboCode Companion Programmable Bot",
    slug: "robocode-companion-programmable-bot",
    category: "Digital Gadgets",
    categorySlug: "digital-gadgets",
    subCategorySlug: "gadget-bundles",
    price: 3250,
    compareAtPrice: 3800,
    rating: 4.9,
    reviewCount: 210,
    imageUrl: "https://images.unsplash.com/photo-1550745165-9bc0b252726f?q=80&w=800&auto=format&fit=crop",
    badge: "Bestseller",
    ageRange: "5-8",
    tags: ["STEM", "Smart", "Creative"],
    description: "Voice-responsive coding companion robot with drag-and-drop visual logic cards, obstacle-avoidance sonar sensors, and expressive LED matrix eyes.",
    curatorNotes: "Teaches algorithmic thinking and sequential logic without requiring screen time. Kids arrange magnetic command tiles and watch the robot execute missions.",
  },
  {
    id: "a8888888-8888-8888-8888-888888888888",
    title: "Artisanal Wooden Train Express Deluxe Network",
    slug: "artisanal-wooden-train-express-deluxe-network",
    category: "Cars & Vehicles",
    categorySlug: "cars-vehicles",
    price: 2450,
    compareAtPrice: 2990,
    rating: 4.8,
    reviewCount: 74,
    imageUrl: "https://images.unsplash.com/photo-1594787318286-3d835c1d207f?q=80&w=800&auto=format&fit=crop",
    badge: "New",
    ageRange: "3-5",
    tags: ["Montessori", "Eco-friendly", "Creative"],
    description: "48-piece solid birchwood track system featuring magnetic engine carriages, bridge arches, turnouts, and realistic scenery elements.",
    curatorNotes: "100% compatible with universal wooden railway tracks. The silky hand-sanded edges ensure safe, splinter-free railway building for hours.",
  },
  {
    id: "a9999999-9999-9999-9999-999999999999",
    title: "Sensory Organic Cotton Swaddle & Teether Bundle",
    slug: "sensory-organic-cotton-swaddle-teether-bundle",
    category: "Gift Combos",
    categorySlug: "gift-combos",
    subCategorySlug: "newborn-babies",
    price: 1950,
    compareAtPrice: 2400,
    rating: 4.9,
    reviewCount: 88,
    imageUrl: "https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?q=80&w=800&auto=format&fit=crop",
    badge: "Bestseller",
    ageRange: "0-1",
    tags: ["Sensory", "Eco-friendly"],
    description: "Breathable GOTS-certified organic cotton muslin blanket paired with a food-grade silicone teething ring and beechwood clip.",
    curatorNotes: "Hypoallergenic, thermoregulating, and machine washable. An essential gift pairing for baby showers and early sensory bonding.",
  },
  {
    id: "b1010101-1010-1010-1010-101010101010",
    title: "Magnetic Marble Run Kinetic Construction Set",
    slug: "magnetic-marble-run-kinetic-construction-set",
    category: "Unique Toys",
    categorySlug: "unique-toys",
    price: 2650,
    compareAtPrice: 3200,
    rating: 4.8,
    reviewCount: 63,
    imageUrl: "https://images.unsplash.com/photo-1558060370-d644479cb6f7?q=80&w=800&auto=format&fit=crop",
    badge: "Sale",
    ageRange: "5-8",
    tags: ["STEM", "Kinetic", "Creative"],
    description: "Translucent magnetic building blocks with winding chutes, vortex funnels, and LED glowing marbles that illuminate the track in the dark.",
    curatorNotes: "Teaches kinetic energy conservation, gravity acceleration, and structural engineering in a dazzling colorful spectacle.",
  },
  {
    id: "b2020202-2020-2020-2020-202020202020",
    title: "Cloud Floating Wooden Wall Shelf",
    slug: "cloud-floating-wooden-wall-shelf",
    category: "Home Decor",
    categorySlug: "home-decor",
    price: 1250,
    compareAtPrice: 1550,
    rating: 4.6,
    reviewCount: 38,
    imageUrl: "https://images.unsplash.com/photo-1513519245088-0e12902e5a38?q=80&w=800&auto=format&fit=crop",
    ageRange: "all",
    tags: ["Creative", "Eco-friendly"],
    description: "Whimsical Scandinavian cloud silhouette floating bookshelf crafted from durable MDF with smooth matte lacquer finish.",
    curatorNotes: "Adds a dreamy, organized accent to nurseries, bedrooms, and study corners with hidden wall mounting hardware included.",
  },
  {
    id: "b3030303-3030-3030-3030-303030303030",
    title: "Celebration Birthday STEM Gift Mega Pack",
    slug: "celebration-birthday-stem-gift-mega-pack",
    category: "Gift Combos",
    categorySlug: "gift-combos",
    subCategorySlug: "birthday-babies",
    price: 4250,
    compareAtPrice: 5200,
    rating: 5.0,
    reviewCount: 49,
    imageUrl: "https://images.unsplash.com/photo-1513151233558-d860c5398176?q=80&w=800&auto=format&fit=crop",
    badge: "Exclusive",
    ageRange: "5-8",
    tags: ["STEM", "Creative"],
    description: "The ultimate birthday gift hamper featuring a mini robotic kit, building tiles, celebration confetti card, and celebratory gift packaging.",
    curatorNotes: "Takes the stress out of birthday gifting. Packed with creative wonder and wrapped in festive sunny yellow ribbons.",
  },
  {
    id: "b4040404-4040-4040-4040-404040404040",
    title: "Interactive Smart Globe with Talking Pen",
    slug: "interactive-smart-globe-with-talking-pen",
    category: "Educational Toys",
    categorySlug: "educational-toys",
    price: 2150,
    compareAtPrice: 2600,
    rating: 4.8,
    reviewCount: 112,
    imageUrl: "https://images.unsplash.com/photo-1596461404969-9ae70f2830c1?q=80&w=800&auto=format&fit=crop",
    badge: "Bestseller",
    ageRange: "5-8",
    tags: ["STEM", "Smart"],
    description: "Illuminated augmented reality world globe with touch-audio pen narrating countries, wildlife, landmarks, and cultural music in 5 languages.",
    curatorNotes: "Makes global geography come alive with quiz challenges, country facts, and a built-in warm LED constellation nightlight.",
  },
  {
    id: "b5050505-5050-5050-5050-505050505050",
    title: "Mirai Smartwatch Kids GPS & Camera",
    slug: "mirai-smartwatch-kids-gps-camera",
    category: "Digital Gadgets",
    categorySlug: "digital-gadgets",
    price: 2750,
    compareAtPrice: 3400,
    rating: 4.7,
    reviewCount: 78,
    imageUrl: "https://images.unsplash.com/photo-1550745165-9bc0b252726f?q=80&w=800&auto=format&fit=crop",
    badge: "New",
    ageRange: "5-8",
    tags: ["Smart", "STEM"],
    description: "Kid-safe 4G smartwatch with real-time location safety, two-way HD voice calling, SOS button, step tracker, and funny selfie filters.",
    curatorNotes: "Gives parents peace of mind and kids fun independence. Features water-resistant silicone strap and parental school-mode timer.",
  },
  {
    id: "b6060606-6060-6060-6060-606060606060",
    title: "Geometric Modern Wall Art Frame Set",
    slug: "geometric-modern-wall-art-frame-set",
    category: "Home Decor",
    categorySlug: "home-decor",
    price: 1890,
    compareAtPrice: 2250,
    rating: 4.9,
    reviewCount: 56,
    imageUrl: "https://images.unsplash.com/photo-1513519245088-0e12902e5a38?q=80&w=800&auto=format&fit=crop",
    ageRange: "all",
    tags: ["Creative"],
    description: "Trio of museum-grade abstract prints in natural oakwood frames with non-glare shatterproof acrylic front.",
    curatorNotes: "Harmonious muted palettes tailored for contemporary living rooms, creative playrooms, and reading nooks.",
  },
  {
    id: "b7070707-7070-7070-7070-707070707070",
    title: "Stunt RC Cyber Stuntbuggy 360",
    slug: "stunt-rc-cyber-stuntbuggy-360",
    category: "Cars & Vehicles",
    categorySlug: "cars-vehicles",
    price: 1650,
    compareAtPrice: 2100,
    rating: 4.6,
    reviewCount: 47,
    imageUrl: "https://images.unsplash.com/photo-1594787318286-3d835c1d207f?q=80&w=800&auto=format&fit=crop",
    badge: "-20%",
    ageRange: "8+",
    tags: ["Kinetic", "STEM"],
    description: "Double-sided tumbling RC vehicle with pneumatic oversized bounce tires, LED chassis underglow, and 2.4GHz remote.",
    curatorNotes: "Flips, spins, and drives over carpets, gravel, and steps without skipping a beat. USB rechargeable battery pack included.",
  },
  {
    id: "b8080808-8080-8080-8080-808080808080",
    title: "Wooden Stacking Rainbow Arc Bridge",
    slug: "wooden-stacking-rainbow-arc-bridge",
    category: "Educational Toys",
    categorySlug: "educational-toys",
    price: 1350,
    compareAtPrice: 1700,
    rating: 4.9,
    reviewCount: 91,
    imageUrl: "https://images.unsplash.com/photo-1596461404969-9ae70f2830c1?q=80&w=800&auto=format&fit=crop",
    badge: "Bestseller",
    ageRange: "1-3",
    tags: ["Montessori", "Sensory", "Eco-friendly"],
    description: "12-piece open-ended nesting rainbow arches cut from solid lime wood and tinted with non-toxic water stains.",
    curatorNotes: "The pinnacle of Waldorf and Montessori open-ended play — becomes bridges, tunnels, doll cradles, and architectural towers.",
  },
  {
    id: "b9090909-9090-9090-9090-909090909090",
    title: "Optical Prism Kaleidoscope Exploration Chamber",
    slug: "optical-prism-kaleidoscope-exploration-chamber",
    category: "Unique Toys",
    categorySlug: "unique-toys",
    price: 1150,
    compareAtPrice: 1450,
    rating: 4.7,
    reviewCount: 34,
    imageUrl: "https://images.unsplash.com/photo-1558060370-d644479cb6f7?q=80&w=800&auto=format&fit=crop",
    badge: "New",
    ageRange: "5-8",
    tags: ["STEM", "Creative"],
    description: "Handheld brass kaleidoscope with interchangeable crystal marble chambers and high-refraction optical glass prisms.",
    curatorNotes: "Transforms ordinary ambient room light and nature textures into breathtaking symmetrical mandalas.",
  },
];

export const FEATURED_PRODUCTS: Product[] = ALL_PRODUCTS.slice(0, 5);
export const TOP_PICKS_PRODUCTS: Product[] = ALL_PRODUCTS.slice(5, 10);

export const BRAND_LOGOS = [
  { name: "Fisher-Price", text: "Fisher-Price" },
  { name: "vtech", text: "vtech" },
  { name: "Melissa & Doug", text: "Melissa & Doug" },
  { name: "mideer", text: "mideer" },
  { name: "winfun", text: "winfun" },
];
